export class AccidentCost{
    AccidentCostID: number;
    AccidentID: number;
    Labour: number ;
    SpareParts: number;
    ValueLoss: number = 0;
    CommercialDiscount: number= 0;
    Excess: number = 0;
    Depreciation: number= 0;
    NetLoss: number;
    RentPerDay: number;
    NetCost: number;
    AccidentTypeID: number;
    TortCompensation: number = 0;
    FinalPartsAmount: number;
    Total: number;
    PreviousAccident: boolean;
    VehicleOwnerName: string;
    ResponsibilityTypeID: number;
    damagePointText: string;
    AccidentNote: string;
    LabourTime: number;
    Percentage: number;
    ValueLossNote: string;
    CreatedOn: Date;
    CreatedBy: number;
    ModifiedByName: string;
    EventDateTime: Date;
    CreatedByName: string;
    OldSpareParts: number;
    SupplierName: string;
    WorkshopName: string;
    RequestID: number;
    OtherExpenses:number;
    OtherExpensesNote:string;
    IsApproved:boolean;
    PreviousSpareParts: number;
    RequestRowNumber:number;
    SerialNo:number;
    Refunds:number;
    ChangePriceReason:string;
    Price:number;
    NetVehicleCostNote:string;
    ResponsibilityPercentage:number;
    IsChecked: boolean = false;
    IsCheckedtemp: boolean = false;
    IsPublished: boolean = false;

}
