import { DamagePoint } from './damage-point';
export class AutomotivePart {
  SupplierID: number;
  UniversalPartID: number;
  AutomotivePartID: number;
  PartName: string;
  MakeID: number;
  ModelID: number;
  ProductionYear: number;
  ImageURL: string;
  OriginalName: string;
  EncryptedName: string;
  CreatedOn: Date;
  CreatedBy: number;
  ModifiedBy: number;
  ModifiedOn: Date;
  IsVerified: boolean;
  IsConditionNew: boolean = true;
  IsConditionUsed: boolean = true;
  IsConditionOriginal: boolean = true;
  IsConditionAfterMarket: boolean = true;
  IsSelected: boolean = false;
  IsPreviouslySelected: boolean = false;
  IsApproved: number = 1;
  UserID: number;
  StatusID: number;
  DamagePointID: string;
  DamageName: string;
  ItemNumber: string;
  Name1: string;
  OptionName: string;
  OptionNumber: string;
  OptionCount: number;
  FinalCode: string;
  Name2: string;
  Name3: string;
  Name4: string;
  Name5: string;
  Name6: string;
  Name7: string;
  Name8: string;
  IsModified: boolean;
  OldAutomotivePartID: number;
  OffersCount: number;
  DamagePointNumber: number;
  NoteInfo:string;
  splitDropDown:boolean = false;
  RejectAndMergeDropDown:boolean = false;
  RejectAndReplaceDropDown:boolean = false;
  RequestCount:number;
  EnglishMakeName:string;
  ArabicMakeName:string;
  EnglishModelName:string;
  ArabicModelName:string;
  DamagePoint: Array<DamagePoint>;
  PageNo: number;
  TotalParts:number;
  OldName1:string;
  OldFinalCode:string;
}
