export class joClaimsSeriesData{
  SeriesID: string;
  MakeName: string;
  ModelName: string;
  BodyCode: string;
  Facelift: string;
  FuelType: string;
  ModelVariant: string = null;
  StartYear: string;
  EndYear: string;
  OverlapYaer: string;
  ImageURL: string;
  YearRange: string;
  isChecked: boolean;
  BodyType: string;
  CarImageEncryptedName: string;
  AccidentID: number;
  CarImageURL: string;
  JCSeriesID: string;
  ImageURL1: string;
  ImageURL2: string;
  StatusID: number;
  CreatedFrom: string;
  CreatedTo: string;
  PageNO: number;
  EnglishMakeName:string;
  EnglishModelName:string;
  face_lift:boolean;
  EncryptedName: string;
  IsNew: boolean;
  UserID: number;
  ModelID: number;
  AccidentCount: number;
  OldJoclaimSeriesID: string;
  OldJoclaimSeriesImage: string;
  OriginalCaseImage: string;
}
