import {Image} from "../../../src/app/models/image";
export class
QuotationPart {

  QuotationPartID: number;
  QuotationID: number;
  RequestedPartID: number;
  Price: number;
  ReferredPrice: number;
  Quantity: number;
  OrderedQuantity: number;
  ConditionTypeID: number;
  NewPartConditionTypeID: number;
  OriginalNewPartConditionTypeID: number;
  ManufacturerID: number;
  IsReferred: boolean;
  IsOrdered: boolean;
  IsTempOrdered: boolean;
  CreatedOn: Date;
  CreatedBy: number;
  ModifiedBy: number;
  ModifiedOn: Date;
  IsDeleted: boolean;
  IsAvailableNow: number = 6;
  DeliveryTime: number;
  WillDeliver: boolean;
  DeliveryCost: number;
  BranchAreaName: string;
  AutomotivePartName: string;
  ManufacturerName: string;
  ConditionTypeName: string;
  SupplierID: number;
  IsIncluded: boolean;
  ManufacturerRegionID: number = 1;
  ManufacturerRegionName: string;
  NoteInfo: string;
  OriginalConditionTypeID: number;
  PartBranchID: number;
  Rating: number;
  AutomotivePartArabicName: string;
  NewPartConditionTypeName: string;
  ConditionTypeNameArabic: string;
  NewPartConditionTypeArabicName: string;
  RejectReason: string;
  AdminRejectNote: string;
  IsAccepted: boolean;
  IsAdminAccepted: boolean;
  IsSelected: boolean;
  RowNumber: number;
  CityID: number;
  IsReceived: boolean;
  ReceivedDate: Date;
  isSpliced: number;
  SupplierName: string;
  SupplierPhoneNumber: string;
  OrderedOn: Date;
  IsRecycled: boolean;
  IsTempRecycle: boolean;
  AcceptedByName: string;
  WorkshopName: string;
  OrderRowNumber: number;
  FillingRate: number;
  StatusID: number;
  DemandedQuantity: number;

  RPConditionTypeName: string;
  RPConditionTypeNameArabic: string;
  RPNewPartConditionTypeName: string;
  RPNewPartConditionTypeArabicName: string;
  ItemRank: number = 0;
  IsBorderBottom: boolean;
  NetPrice: number;
  IsRecommended: number;
  PriceChanged: boolean = false;
  MatchingOfferSortNo: number;
  OfferSortNo: number;
  RejectedPartImage?: Array<Image>;
  total: number =0 ;
  IsReturn: boolean;
  IsWsAccepted: boolean;
  WsRejectionNote: string;
  IsPartialSellings: boolean;
  IsModified: boolean;
  POPdfURL: string;
  POPdfUrl: string;
  PartStatus: number;
  QuotationStatus: number;
  PreviousPrice: number;
  UsedAVGPrice: number;
  NEWAVGPrice: number;
  AftermarketAVGPrice: number;
  TotalOffers: number;
  AutomotivePartID: number;
  hidePartDetail: boolean= false;
  WithoutDiscountPrice: number;
  UsedPrice: number;
  NewPrice: number;
  AftermarketPrice: number;
  UsedCreatedOn:Date;
  NewCreatedOn:Date;
  AftermarketCreatedOn:Date;
  SupplierType: number;
  RecommendationType: number;
  RejectedWorkshopPartReasonID: number;
  AvgPrice:number;
  MinimumPrice:number;
  MaximumPrice:number;
  RequestID: number;
  IsUniversal: number;
}
