import { Accident } from '../models/accident';
export class Request extends Accident {
  RequestID: number;
  RequestNumber: number;
  MakeID: number;
  ModelID: number;
  ProductionYear: number;
  AccidentID: number;
  PlateNo: string;
  CompanyID: number;
  CityID: number;
  StatusID: number;
  StatusName: string;
  ArabicStatusName: string;
  CreatedOn: Date;
  PublishedOn: Date;
  CreatedBy: number;
  ModifiedBy: number;
  ModifiedOn: Date;
  IsDeleted: boolean;
  VIN: string;
  YearCode: string;
  MakeName: string;
  ModelCode: string;
  ArabicMakeName: string;
  ArabicModelName: string;
  AccidentNo: string;
  CPPhone: string;
  ICName: string;
  CPName: string;
  DemandID: number;
  QuotationID: number;
  SupplierID: number;
  TotalQuotations: number;
  LogoURL: string;
  CountryName: string;
  AddressLine1: string;
  SupplierName: string;
  WillDeliver: boolean = false;
  DeliveryCost: number;
  VehicleOwnerName: string;
  CreatedSince: string;
  CreatedSinceArabic: string;
  WorkshopName: string;
  WorkshopCityName: string;
  WorkshopAreaName: string;
  OrderByName: string;
  BiddingHours: number = 24;
  ShowText: boolean = false;
  ShowICText: boolean = false;
  IsBiddingTimeExpired: number;
  BiddingDateTime: Date;
  IsPublished: boolean;
  RejectionCount: number;
  IsApproved: boolean;
  UserName: string;
  AccidentTypeName: string;
  ArabicAccidentTypeName: string;
  CreatedOnAccident: string;
  IsReady: boolean = false;
  IsCarRepairStarted: boolean = false;
  CompanyAddress1: string;
  CompanyAddress2: string;
  CompanyCountryName: string;
  SpCountryName: string;
  SpCityname: string;
  SpAddressLine1: string;
  InvoiceImage: string;
  CityName: string;
  JoCancelOrderNote: string;
  IcCancelOrderNote: string;
  POTotalAmount: number;
  IsNotAvailable: boolean;
  IsDiscountAvailable: boolean = false;
  DiscountValue: number;
  Comment: string;
  SerialNo: number;
  ESignatureURL: string;
  TotalOffersCount: number;
  BestOfferPrice: number;
  DiscountedPrice: number;
  BestMinOfferPrice: number;
  BestOfferQuotationID: number;
  BestOfferSupplierID: number;
  IsOldPartsRequired: boolean = true;
  RejectedOffersCount: number;
  TotalRequestedParts: number;
  DemandCreatedOn: Date;
  DemandCreatedSince: string;
  DemandCreatedSinceArabic: string;
  QuotationsCount: number;
  OriginalDiscountedPrice: number;
  OriginalPrice: number;
  RecommendedTotalPrice: number;
  LowestMatchingOffer: number;
  LowestNotMatchingOffer: number;
  SavingByRecommended: number;
  PhoneNumber: string;
  WebsiteAddress: string;
  FaxNumber: string;
  CompanyName: string;
  UserID: number;
  Email: string;
  QuotationSummaryPdfUrl: string;
  ClearanceSummaryPdfUrl: string;
  AccidentHappendOn:Date;
  RequestRowNumber: number;
  AllOffersPdfUrl: string;
  BestMinOfferMatchingPrice: number;
  BestOfferMatchingQuotationID: number;
  BestOfferMatchingSupplierID: number;
  TotalNotAvailableQuotations: number;
  IsPurchasing: boolean = false;
  IsEditPurchasing: boolean = false;
  EventDateTime: Date;
  ModifiedByName: string;
  CreatedByName: string;
  CreatedByEmail: string;
  ModifiedByEmail: string;
  LowestMatchingOfferPrice:number;
  CustomerESignatureURL:string;
  POPdfUrl:string;
  OrderOn: Date;
  TotalRepairOrderAmount: number;
  AccidentCreatedOn: Date;
  ReturnReason: string;
  PONote =  'ارسال الفاتورة لنا للتسديد بعد توقيع الفاتورة باستلام القطع من الكراج';
  SupplierPhone: string;
  IsLowestMatching: boolean;
  IsPartialSellings: boolean = false;
  WorkshopPhone: string;
  TotalTaskAmount: number;
  ROPdfURL: string;
  AccidentCount: number;
  CarCost: number;
  avgCarCost: number;
  LabourPrice: number;
  purchaseOrderDropDown: boolean = false;
  IsMakeChange: boolean = false;
  IsRequestWorkshopIC: boolean;
  JoReviewNote: string;
  HalfSupplierName: string;
  IsHalfNameShow: boolean;
  spaceCount: number;
  DraftID:number;
  NumberRequestedPart: number;
  POApprovalOn: Date;
  FirstRequestLabourPrice: number;
  NotPurchasingLMOReason:string;
  IsTaskApproved : boolean;
  IsPartApproved : boolean;
  RequestPdfUrl: string | any;
  EstimatedPrice: number;
  IsInstantPrice:boolean = false;
  InspektLabToken: string;
  InspektLabCaseID: string;
}
