import { User } from './user';
export class Supplier extends User {
  SupplierID: number;
  SupplierName: string;
  LogoURL: string;
  CityID: number;
  CountryID: number;
  AddressLine1: string;
  AddressLine2: string;
  GoogleMapLink: string;
  CPFirstName: string;
  CPLastName: string;
  CPPositionID: number;
  CPPhone: string;
  CPEmail: string;
  StatusID: number;
  CreatedOn: Date;
  CreatedBy: number;
  ModifiedBy: number;
  ModifiedOn: Date;
  IsDeleted: boolean;
  CityName: string;
  CityNameArabic: string;
  CountryName: string;
  CountryNameArabic: string;
  CPPositionName: string;
  CPPositionArabicName: string;
  TypeName: string;
  StatusName: string;
  ArabicStatusName: string;
  RegistrationNumber: string;
  IsSellUsed: string;
  RejectNote: string;
  ShowText: boolean = false;
  Rating: number;
  AlreadyApplied: number;
  OffersCount: number;
  RequestID: number;
  TotalDemands: number;
  ApplyRatio: number;
  PaymentTypeID: number = 68;
  PaymentTypeName: string;
  PaymentTypeArabicName: string;
  AppVersion:string;
  TotalPO:number;
  TotalPOAmount:number;
  IBAN: string;
  SupplierType: number;
  ArabicTypeName: string;
  IsBlocked: boolean;
  ContactPerson:string;
  TotalRequestsReceived:number;
 TotalRequestsApplied:number;
 SuccessRate:number;
 AccountID: number;
 AccountNumber: string;
 UserID: number;
}
