import { Image } from "./image";

export class TechnicalNotes{
    TechnicalNoteID: number;
    AccidentNo: string;
    ReportSubject: string;
    FromEmployee: string;
    ContractNumber: string;
    DebitAccount: number;
    CreditBalance: number;
    ToEmployee: string;
    InsuredAmount: number;
    Repair: boolean;
    PrevioutAccidentRecord: string;
    Premium: number;
    Compensation: number;
    InsuredResult: string;
    AccidentResponsibility: number;
    KrokiSketch: string;
    PoliceReport: string;
    Cause: string;
    IVDriverFault: string;
    TPLDriverFault: string;
    ReverseCase: string;
    PreviousAccident: boolean;
    PreliminaryAgreementInsured: string;
    DisagreementPoints: string;
    ProposalSolution: string;
    LossAdjusterName: string;
    LossAdjusterReportResult: string;
    TechnicalExplanation: string;
    CompensationProposal: string;
    Recovery: number;
    PaidCompensation: number;
    FullPeriodPremium: number;
    LossAdjusterReport: number;
    CompensationCost: number;
    MarketValue: number;
    ApproxSalvageAmount: number;
    CompensationAmount: number;
    SalvageBestAmount: number;
    NetLoss: number;
    InjuredName: string;
    InjuredAge: number;
    InjuredLevel: string;
    LegalOpenion: string;
    MedicalOpenion: string;
    MedicalExplanation: string;
    TechnicalProcedure: string;
    TreatmentExpense: number;
    DisabilityCompensation: number;
    FutureOperation: number;
    FinalMedicalReportUrl: string;
    PenaltyRulingDecisionUrl: string;
    RegionalCommitteUrl: string;
    LogoURL: string;
    ToDate: string;
    FromDate: string;
    ModifiedBy: number;
    CompanyID: number;
    ObjectTypeID: number;
    TRTotalAmount: number;
    CreatedOn: Date;
    AssignLossAdjuster: boolean;
    Note: string;
    ComVehicleOwnerName: string;
    ComPlateNo: string;
    ComCarMake: string;
    ComCarModel: string;
    ComCarYear: string;
    ComDamagePoints: string;
    CINote: string;
    TPLNote: string;
    TotalLossNote: string;
    HINote: string;
    ComAccidentNote: string;
    EventDateTime: Date;
    ModifiedByName: string;
    CreatedByName: string;
    ContractNotes:string;
    ATCElabour:number= 0;
    ATCEsparePart:number= 0;
    ATCEValueLoss:number= 0;
    ATCETortCompensation:number= 0;
    ATElabour:number = 0;
    ATEsparePart:number = 0;
    ATEValueLoss:number = 0;
    ATETortCompensation:number = 0;
    TPReserves :boolean = false;
    ThirdTeamReserve1 :number=0;
    ThirdTeamReserve2 :number=0;
    ThirdTeamReserve3 :number=0;
    ThirdTeamReserve4 :number=0;
    ThirdTeamReserve5 :number=0;
    BodilyHarm1 :number=0;
    BodilyHarm2 :number=0;
    BodilyHarm3 :number=0;
    BodilyHarm4 :number=0;
    BodilyHarm5 :number=0;
    COMReserves :boolean = false;
    CPReserve:number;
}
